### PR TITLE
chore: add screenshots

### PR DESCRIPTION
**Pull request by amrbashir**
Screenshots added:
- [x] Windows
- [ ] macOS

### CODE REVIEW

**Comment by LoganDark** [comment]
Do you need a macOS screenshot? I have a spare machine I could use to take a nice Retina screenshot (on 10.14)

**Comment by amrbashir** [comment]
@LoganDark yeah, that would be fantastic.

**Comment by LoganDark** [comment]
> @LoganDark yeah, that would be fantastic.

It'll have to "resolve deltas" for the next few hours in order to build anything, but I'll let you know when it's done.

image

(the actual screenshot will be higher-quality than this)

**Comment by LoganDark** [comment]
image

or with less padding:

image

**Comment by amrbashir** [comment]
@LoganDark Thank you so much, it is perfect.

**Pull request merged**
